apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: swd-fe-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/kadeksuryam-project-1/infrastructure
    targetRevision: HEAD
    path: k8s-manifests/stand-with-dorayaki-fe
    directory:
      recurse: true 
  destination: 
    server: https://kubernetes.default.svc
    namespace: swd

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
