apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: stand-with-dorayaki-be
  namespace: swd
spec:
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 50
        type: Utilization
    type: Resource
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: stand-with-dorayaki-be
